[2024-07-02T17:24:14.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T17:24:15.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-07-02T17:24:15.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-07-02T17:24:15.210+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-02T17:24:15.733+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_csv_to_mysql> on 2023-01-03 00:00:00+00:00
[2024-07-02T17:24:16.012+0000] {standard_task_runner.py:63} INFO - Started process 1077 to run task
[2024-07-02T17:24:16.186+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_pet_adoption_data_to_mysql', 'ingest_csv_to_mysql', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ingest_pet_adoption_data_to_mysql.py', '--cfg-path', '/tmp/tmpoftlstvc']
[2024-07-02T17:24:16.298+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask ingest_csv_to_mysql
[2024-07-02T17:24:17.496+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-03T00:00:00+00:00 [running]> on host 72210ec1b5c5
[2024-07-02T17:24:19.779+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_pet_adoption_data_to_mysql' AIRFLOW_CTX_TASK_ID='ingest_csv_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-07-02T17:24:19.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T17:24:56.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T17:24:56.137+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_pet_adoption_data_to_mysql.py", line 15, in ingest_csv_to_mysql
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-07-02T17:24:56.183+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_pet_adoption_data_to_mysql, task_id=ingest_csv_to_mysql, run_id=scheduled__2023-01-03T00:00:00+00:00, execution_date=20230103T000000, start_date=20240702T172415, end_date=20240702T172456
[2024-07-02T17:24:56.273+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task ingest_csv_to_mysql ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 1077)
[2024-07-02T17:24:56.350+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T17:24:56.444+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T17:24:56.454+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
