[2024-07-02T17:29:35.089+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T17:29:35.274+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2024-07-02T17:29:35.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-07T00:00:00+00:00 [queued]>
[2024-07-02T17:29:35.355+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-02T17:29:35.500+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_csv_to_mysql> on 2023-01-07 00:00:00+00:00
[2024-07-02T17:29:35.529+0000] {standard_task_runner.py:63} INFO - Started process 1599 to run task
[2024-07-02T17:29:35.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_pet_adoption_data_to_mysql', 'ingest_csv_to_mysql', 'scheduled__2023-01-07T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ingest_pet_adoption_data_to_mysql.py', '--cfg-path', '/tmp/tmpfoi0n3vs']
[2024-07-02T17:29:35.574+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask ingest_csv_to_mysql
[2024-07-02T17:29:35.936+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_pet_adoption_data_to_mysql.ingest_csv_to_mysql scheduled__2023-01-07T00:00:00+00:00 [running]> on host 72210ec1b5c5
[2024-07-02T17:29:36.623+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_pet_adoption_data_to_mysql' AIRFLOW_CTX_TASK_ID='ingest_csv_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-07T00:00:00+00:00'
[2024-07-02T17:29:36.629+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T17:31:26.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T17:31:26.262+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_pet_adoption_data_to_mysql.py", line 18, in ingest_csv_to_mysql
    df = spark.read.csv(r"C:\Users\Indah Permata\Documents\dbimbing_final_project\data\pet_adoption_data.csv", header=True, inferSchema=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 740, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: C:%5CUsers%5CIndah%20Permata%5CDocuments%5Cdbimbing_final_project%5Cdata%5Cpet_adoption_data.csv
[2024-07-02T17:31:27.147+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingest_pet_adoption_data_to_mysql, task_id=ingest_csv_to_mysql, run_id=scheduled__2023-01-07T00:00:00+00:00, execution_date=20230107T000000, start_date=20240702T172935, end_date=20240702T173127
[2024-07-02T17:31:27.518+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task ingest_csv_to_mysql (java.net.URISyntaxException: Relative path in absolute URI: C:%5CUsers%5CIndah%20Permata%5CDocuments%5Cdbimbing_final_project%5Cdata%5Cpet_adoption_data.csv; 1599)
[2024-07-02T17:31:27.810+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T17:31:27.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T17:31:27.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
