[2024-05-10T15:34:02.034+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T15:34:02.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mysql_to_hive_dibimbing_karyawan.load_to_hive manual__2024-05-10T15:06:09.742170+00:00 [queued]>
[2024-05-10T15:34:02.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mysql_to_hive_dibimbing_karyawan.load_to_hive manual__2024-05-10T15:06:09.742170+00:00 [queued]>
[2024-05-10T15:34:02.104+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-10T15:34:02.137+0000] {taskinstance.py:2330} INFO - Executing <Task(HiveOperator): load_to_hive> on 2024-05-10 15:06:09.742170+00:00
[2024-05-10T15:34:02.151+0000] {standard_task_runner.py:63} INFO - Started process 1987 to run task
[2024-05-10T15:34:02.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mysql_to_hive_dibimbing_karyawan', 'load_to_hive', 'manual__2024-05-10T15:06:09.742170+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/etl_mysql_to_hive_dibimbing_karyawan.py', '--cfg-path', '/tmp/tmpdooo_zfm']
[2024-05-10T15:34:02.163+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask load_to_hive
[2024-05-10T15:34:02.272+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mysql_to_hive_dibimbing_karyawan.load_to_hive manual__2024-05-10T15:06:09.742170+00:00 [running]> on host feac594d54b9
[2024-05-10T15:34:02.420+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'load_to_hive', field 'hql'. Template: "\n            INSERT INTO dibimbing.karyawan (id, nama) VALUES\n            {% for row in xcom %}\n            ({{ row[0]}}, '{{row[1] }}')\n            (% if not loop.last %)\n            ,\n            (% endif %) \n            {% endfor %}\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'xcom' is undefined
[2024-05-10T15:34:02.426+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'xcom' is undefined
[2024-05-10T15:34:02.445+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_mysql_to_hive_dibimbing_karyawan, task_id=load_to_hive, run_id=manual__2024-05-10T15:06:09.742170+00:00, execution_date=20240510T150609, start_date=20240510T153402, end_date=20240510T153402
[2024-05-10T15:34:02.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 133 for task load_to_hive ('xcom' is undefined; 1987)
[2024-05-10T15:34:02.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T15:34:02.542+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T15:34:02.550+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
